apiVersion: v1
kind: Service
metadata:
  name: tunnel-proxy
  labels:
    run: tunnel-proxy
spec:
  ports:
    - port: 18002
      protocol: TCP
  selector:
    run: tunnel-proxy
  # externalIPs:
  #   - xxx.xxx.xxx.xxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-proxy
spec:
  selector:
    matchLabels:
      run: tunnel-proxy
  replicas: 5
  template:
    metadata:
      labels:
        run: tunnel-proxy
    spec:
      containers:
        - name: tunnel-proxy
          image: 172.23.254.162:5000/tunnelserver:test
          ports:
            - containerPort: 18002