apiVersion: v1
kind: Service
metadata:
  name: tunnel-kuaidaili
  labels:
    run: tunnel-kuaidaili
spec:
  ports:
    - port: 18002
      protocol: TCP
  selector:
    run: tunnel-kuaidaili
  # externalIPs:
  #   - xxx.xxx.xxx.xxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-kuaidaili
spec:
  selector:
    matchLabels:
      run: tunnel-kuaidaili
  replicas: 3
  template:
    metadata:
      labels:
        run: tunnel-kuaidaili
    spec:
      containers:
        - name: tunnel-kuaidaili
          image: docker-registry.istarshine.net.cn:5000/tunnelproxy:kuaidaili
          ports:
            - containerPort: 18002